# Introduction to numpy -- following along from Treehouse

In [3]:
import numpy as np
np.__version__

'1.16.2'

## Differences between lists and numpy arrays:

- lists are flexible and easy to modify. The size of an array are immutable after their creation.
- All the elements of an array must be of the same data type.

In [4]:
gpas_as_list = [4.0, 3.286, 3.5]

In [5]:
gpas_as_list.append(4.0)

In [6]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [7]:
gpas = np.array(gpas_as_list)

In [8]:
study_minutes = np.zeros(100, np.uint16)

In [9]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [10]:
study_minutes[0] = 150

In [11]:
first_day_minutes = study_minutes[0]

In [12]:
first_day_minutes

150

In [13]:
type(first_day_minutes)

numpy.uint16

In [14]:
study_minutes[1]=60

## Creation
* Random State: A predefined set of random numbers. This is found in the np.random package
    * Allows you to select the same random numbers as somebody else
* Appending Rows: You can redefine arrays by appending another array alongide
    * To do this, you must select the array you want to append to, the data which you want to append, and the location you wish to append this.
    * Rather than a simple redefinition, you are creating a whole new array - the shape of an array is naturally immutable.
## Indexing
* Shortcut(tuple): One can index in multiple dimensions by separating the values in the square brackets [3, 4]. 
* Fancy indexing: By having an internal set of square brackets, you may select multiple entries at once [[3, 4]].


In [15]:
study_minutes[2:6]=[80,60,30,90]

In [18]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype = np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [19]:
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [23]:
index = np.array([
    [3,8],
    [0,1]
])
fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [24]:
study_minutes = np.append(study_minutes, fake_log, axis = 0)

In [25]:
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0, 132, 122, 128,  44,
       136, 129, 101,  95,  50, 132, 151,  64, 104, 175, 117, 146, 139,
       129, 133, 176,  98, 160, 179,  99,  82, 142,  31, 106, 117,  56,
        98,  67, 121, 159,  81, 170,  31,  50,  49,  87, 179,  51, 116,
       177, 118,  78, 171, 117,  88, 123, 102,  44,  79,  31, 108,  80,
        59, 137,  84,  93, 155, 160,  67,  80, 166, 164,  70,  50, 102,
       113,  47, 131, 161, 118,  82,  89,  81,  43,  81,  38, 11

In [26]:
fake_log < 60

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
        True, False,  True, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False])

In [27]:
fake_log[fake_log < 60]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [28]:
orders = np.array([
    [2, 0, 0, 0],
    [4, 1, 2, 2],
    [0, 1, 0, 1],
    [6, 0, 1, 2]
])


In [29]:
totals = np.array([3, 20.50, 10, 14.25])

In [30]:
np.linalg.solve(orders, totals)

array([1.5 , 8.  , 1.25, 2.  ])